### ISSUE TITLE
Help~, I have High CPU HZ problem when use in cluster mode

### ISSUE THREAD

**Issue by wxmayifei** [dahomey-technologies/rustis#43] opened 2023-08-24 09:11 UTC
> Redis Version: 7.0.12

I use the connection with bb8 pool in cluster mode, the following is some code i written

```
static mut REDIS_POOL: Option<Pool<PooledClientManager>> = None;
/// this function will be invoked on app start
pub async fn init() {
  let config =rustis::client::Config {
     // cluster config
  };
  let manager = PooledClientManager::new(config)?;
      unsafe {
          REDIS_POOL = Some(
              rustis::bb8::Pool::builder()
                  .idle_timeout(Some(redis_settings.get_idle_timeout()))
                  .max_size(redis_settings.pool_size)
                  .build(manager)
                  .await?,
          )
      }
}

#[inline]
pub async fn get_pooled_client<'a>(
) -> Result<PooledConnection<'a, PooledClientManager>, RunError<rustis::Error>> {
    let pool = unsafe { REDIS_POOL.as_ref().expect("Can't read RedisPool") };
    pool.get().await
}

pub async fn blpop_key(key: &str) -> AppResult<Option<(String, BulkString)>> {
    let client = get_pooled_client().await?;
    Ok(client.blpop(key, 25.0).await?)
}

pub async fn rpush(key: &str, value: &[u8]) -> AppResult<usize> {
    let client = get_pooled_client().await?;
    Ok(client.rpush(key, value).await?)
}

pub async fn subscribe() {
     let channels = vec![ ];
        // 
        let client = match get_pooled_client().await {
            Ok(client) => client,
            Err(err) => {
                log::debug!(
                    "Error on get redis connection on subscribe default, {}",
                    err.to_string()
                );
                return;
            }
        };
        match client.subscribe(channels).await {
            Ok(mut pub_sub_stream) =>{
                match pub_sub_stream.next().await { 
                  .......
               }
            } ,
            Err(err) => {
                log::debug!("Error on subscribe , {}", err.to_string());
            }
       }
}

```

## After Process Start
> Time 1：all the connection are  established to redis server, the following socket fd status is outputed by the `lsof -p` command

```
xnebula-h 30179 root   11u     IPv4             221212      0t0      TCP TEST-EAP-APP-3:57752->192.168.3.72:6383 (ESTABLISHED)
xnebula-h 30179 root   12u     IPv4             221215      0t0      TCP TEST-EAP-APP-3:57758->192.168.3.72:6383 (ESTABLISHED)
xnebula-h 30179 root   13u     IPv4             221213      0t0      TCP TEST-EAP-APP-3:43418->192.168.3.71:6381 (ESTABLISHED)
xnebula-h 30179 root   14u     IPv4             221214      0t0      TCP TEST-EAP-APP-3:47798->192.168.3.70:redis (ESTABLISHED)
xnebula-h 30179 root   15u     IPv4             221216      0t0      TCP TEST-EAP-APP-3:43424->192.168.3.71:6381 (ESTABLISHED)
xnebula-h 30179 root   16u     IPv4             221217      0t0      TCP TEST-EAP-APP-3:47804->192.168.3.70:redis (ESTABLISHED)
xnebula-h 30179 root   17u     IPv4             208636      0t0      TCP TEST-EAP-APP-3:57766->192.168.3.72:6383 (ESTABLISHED)
xnebula-h 30179 root   18u     IPv4             208637      0t0      TCP TEST-EAP-APP-3:43432->192.168.3.71:6381 (ESTABLISHED)
xnebula-h 30179 root   19u     IPv4             208638      0t0      TCP TEST-EAP-APP-3:47812->192.168.3.70:redis (ESTABLISHED)

```

> Time 2：after some seconds, the socket fd status, some socket was in `CLOSE_WAIT` status
```
xnebula-h 30179 root   11u     IPv4             221212      0t0      TCP TEST-EAP-APP-3:57752->192.168.3.72:6383 (CLOSE_WAIT)
xnebula-h 30179 root   12u     IPv4             220540      0t0      TCP TEST-EAP-APP-3:57780->192.168.3.72:6383 (ESTABLISHED)
xnebula-h 30179 root   13u     IPv4             221213      0t0      TCP TEST-EAP-APP-3:43418->192.168.3.71:6381 (CLOSE_WAIT)
xnebula-h 30179 root   14u     IPv4             221214      0t0      TCP TEST-EAP-APP-3:47798->192.168.3.70:redis (ESTABLISHED)
xnebula-h 30179 root   15u     IPv4             220541      0t0      TCP TEST-EAP-APP-3:43446->192.168.3.71:6381 (ESTABLISHED)
xnebula-h 30179 root   16u     IPv4             220542      0t0      TCP TEST-EAP-APP-3:47826->192.168.3.70:redis (ESTABLISHED)
```
when after `Time 2`, the CPU will become high
the redis server has configured timeout with 60 seconds 

Then use flamegraph to trace CPU, the following is the cpu usage svg captured by flamegraph
![003](https://github.com/dahomey-technologies/rustis/assets/4023908/51e24f42-5950-468d-970e-62bb2404fa2d)

 According the svg, there has about 96% CPU usage by
 `rustis::network::network_handler::NetworkHandler::connect::_{{closure}}::_{{closure}}`
`rustis::network::network_handler::NetworkHandler::network_loop::_{{closure}}::_{{closure}}::_{{closure}}`

This issue can be reproduced in cluster mode, when run in singleton mode, the issue disappears

please help ~~~
thank you ~

**Comment by mcatanzariti** [comment] 2023-08-25 03:09
Hi @wxmayifei,

Do you have a full sample to reproduce the problem?
What is the rustis configuration (client:: Config)?
Does the CPU problem occur only during the connection?
What is the bb8 idle timeout?
It may be not related but why do you need unsafe code?
Have you tried the cluster mode with a multiplexed client instead of bb8 ? Have you experienced the same problems?

Cheers,

Michaël

**Comment by wxmayifei** [comment] 2023-08-25 06:31
@mcatanzariti 
very thanks for your reply~

### i found this issue was caused by the subscribe function at present in cluster mode

> What is the rustis configuration (client:: Config)?
```
 let mut nodes = vec![];
 nodes.push(("192.168.128.131".to_string() , 6401u16));
 nodes.push(("192.168.128.131".to_string() , 6402u16));
 let config = rustis::client::Config {
        server:   ServerConfig::Cluster(ClusterConfig { nodes }),
        username: XXXXx,
        password: XXXXX,
        database: 0,
        connect_timeout: Duration::from_secs(5),
        command_timeout: Duration::from_secs(5),
        auto_resubscribe: true,
        auto_remonitor: false,
        connection_name,
        keep_alive: None,
        no_delay: true,
        max_command_attempts: 3,
        retry_on_error: true,
    };
```

> Does the CPU problem occur only during the connection?
What I observed is this, at that time, the process had no other tasks running


> What is the bb8 idle timeout?
45s

> It may be not related but why do you need unsafe code?
it's only a static varable, and it inited at process start

> Have you tried the cluster mode with a multiplexed client instead of bb8 ? Have you experienced the same problems?
i use the blocking command such as blpop, subscribe, can't use multiplex connection, this problem can be reproduced

## after i add log
network/network_handler.rs, `async fn network_loop(&mut self)` about at line : 138
···
    async fn network_loop(&mut self) -> Result<()> {
        let mut counter = 0u64;                                       // add this line
        loop {
            counter += 1;                                                   // add this line
            log::debug!("run network_loop {}", counter);   // add this line
            select! {
                msg = self.msg_receiver.next().fuse() => {
                    if !self.handle_message(msg).await { break; }
                } ,
                value = self.connection.read().fuse() => {
                    self.handle_result(value).await;
                }
            }
        }

        debug!("[{}] end of network loop", self.tag);
        Ok(())
    }
···
network/network_handler.rs, `async fn handle_result(&mut self, result: Option<Result<RespBuf>>)` about at line : 367
```
   async fn handle_result(&mut self, result: Option<Result<RespBuf>>) {
        log::debug!("run handle_result {:?}", result);   // add this line
        match result {
            Some(result) => match self.status {
                Status::Disconnected => (),
        ........................
  }
```


network/cluster_connection.rs , in the method `pub async fn read(&mut self)` about at line : 488

```
   let read_futures = self.nodes.iter_mut().map(|n| n.connection.read().boxed());
            let (result, node_idx, _) = future::select_all(read_futures).await;

            if let Some(Ok(bytes)) = &result {
                if bytes.is_push_message() {
                    return result;
                }
            }

            let node_id = &self.nodes[node_idx].id;
            log::info!("Receive Result : {:?}", result);   // I add log at here
            let Some((req_idx, sub_req_idx)) =
                self.pending_requests
                    .iter()
                    .enumerate()
                    .find_map(|(req_idx, req)| {
                        let sub_req_idx = req
                            .sub_requests
                            .iter()
                            .position(|sr| sr.node_id == *node_id && sr.result.is_none())?;
                        return Some((req_idx, sub_req_idx));
                    })
            else {
                return Some(Err(Error::Client(format!(
                    "[{}] Received unexpected message",
                    self.tag
                ))));
            };

```

**Comment by wxmayifei** [comment] 2023-08-25 08:05
this issue has not happened again since I configured the redis server's timeout with the value 0

but in prod env, we has configured the value with 60, I cannot and dare not modify this setting

**Comment by mcatanzariti** [comment] 2023-08-25 08:10
Can you give the exact the server config name please ?

For information, you can use a dedicated rustis Client instance for blocking commands or subscription. The pb is when you share this instance with orher usages because the underlying connection will be blocked by the blocking commands. Thus no need to use a bb8 connection pool.

**Comment by wxmayifei** [comment] 2023-08-25 08:22
> Can you give the exact the server config name please ?
> the server is in the LAN, please wait a moment, I will deploy a cluster on public network,

> you can use a dedicated rustis Client instance for blocking commands or subscription. 
> Yes , i just did it, but still have the same issue with the timeout value of 60s

**Comment by wxmayifei** [comment] 2023-08-25 09:01
@mcatanzariti 

please try the following redis erver, use the subscribe feature 

```
nodes: 43.155.130.247:6401
       43.155.130.247:6402
       43.155.130.247:6403
       43.155.130.247:6404
       43.155.130.247:6405
       43.155.130.247:6406

password: 111111

```

then will reproduce the issue

thank you for youe help~

**Comment by mcatanzariti** [comment] 2023-08-30 05:56
@wxmayifei yes please!

**Comment by wxmayifei** [comment] 2023-08-30 08:18
> @wxmayifei yes please!

but there has a question,  the reconnect_interval will block both network write and read，I cannot get a better solution based on this ......

**Comment by mcatanzariti** [comment] 2023-08-30 19:33
@mstyura any thoughts or suggestions?

**Comment by mstyura** [comment] 2023-08-31 19:56
Hi! Sorry for a delayed response. I haven't deeply looked at this problem yet, but would like to share recent observation from app which uses `rustis`. I've also experienced sort of busy-loop on production server in case of 1 or 2 nodes from redis cluster are re-started while `rustis` having connection to it. I also haven't dive deeply at that problem yet, but first observation was around unexpected response from server which lead either to panic or to busy loop. Will try to reproduce it in controlled environment to find a proper fix. Perhaps these problems somehow originate from the same root cause...

**Comment by wxmayifei** [comment] 2023-09-03 16:18
@mcatanzariti  @mstyura 
Thanks. I am looking forward to that.

**Comment by mcatanzariti** [comment] 2023-12-29 00:49
fixed in https://github.com/dahomey-technologies/rustis/commit/29b2b5f66f058bec3b8374fec6eb548b1f2ce472

**Closed by mcatanzariti** 2023-12-29 00:49 UTC
